# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nauczyciel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Nauczyciel',
            },
        ),
        migrations.CreateModel(
            name='Przedmiot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('skrot', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Przedmiot',
            },
        ),
        migrations.CreateModel(
            name='Sprawdzian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc_uczniow', models.IntegerField()),
                ('data_sprawdzianu', models.DateField()),
                ('nauczyciel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Nauczyciel')),
            ],
            options={
                'db_table': 'Sprawdzian',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc_zadan', models.IntegerField()),
                ('maks_ilosc_punktow', models.IntegerField()),
                ('temat', models.CharField(max_length=50)),
                ('data_dodania', models.DateField()),
                ('active', models.BooleanField()),
                ('przedmiot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Przedmiot')),
            ],
            options={
                'db_table': 'Test',
            },
        ),
        migrations.CreateModel(
            name='Zadanie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer', models.IntegerField()),
                ('ilosc_punktow_uczniow', models.DecimalField(decimal_places=2, max_digits=5)),
                ('maks_ilosc_punktow', models.IntegerField()),
                ('sprawdzian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Sprawdzian')),
            ],
            options={
                'db_table': 'Zadanie',
            },
        ),
        migrations.AddField(
            model_name='sprawdzian',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Test'),
        ),
    ]
