# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170129_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='active',
        ),
        migrations.RemoveField(
            model_name='zadanie',
            name='aktywny',
        ),
        migrations.AddField(
            model_name='test',
            name='aktywny',
            field=models.BooleanField(default=True),
        ),
    ]
